using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using System.IO;
using System.Text;
using System;

public class NewParticleController : MonoBehaviour
{
    //no dimention value
    private const float KgCoefficient = 0.00000000000001f;
    private const float MCoefficient = 0.000001f;

    //simulation value
    private const float Pi = Mathf.PI;
    private int n, i, j;
    private float stepTime, x, y, z;
    private Rigidbody[] MagneticParticleRB;
    private Transform[] MagneticParticleTrans;
    public Button ON_MagButton, OFF_MagButton, TimeMagButton;
    public SetParticle setParticle;
    public GameObject[] MagneticParticle;
    public int step;
    public int ChangeStep; //å¤‰åŒ–Step
    public float diameter;
    [HideInInspector] public int particleNumber;

    //noise value
    public bool useTrans, useBrown, useRandPow;
    public float pow;
    private const float eta = 0.001f; //æ°´ã®ç²˜æ€§ä¿‚æ•° 8.9*10^-4
    private const float T = 300; //çµ¶å¯¾æ¸©åº¦ K
    private const float kb = 0.00000000000000000000001f; //ãƒœãƒ«ãƒ„ãƒãƒ³å®šæ•° 1.38*10^-23
    private float gamma; //ç²˜æ€§æŠµæŠ—
    private float D; //æ‹¡æ•£ä¿‚æ•°
    private Vector3 V; //é€Ÿåº¦
    private Vector3 nowPos; //å‰ã®ä½ç½®ã¨ã®æ¯”è¼ƒç”¨
    private Vector3[] brownX; //ãƒ–ãƒ©ã‚¦ãƒ³é‹å‹•ã®å¤‰ä½
    private Vector3[] BeforePosition; //å‰ã‚¹ãƒ†ãƒƒãƒ—ã®ä½ç½®ã‚’ä¿å­˜
    private Vector3[] brownX_before;

    //mag value
    public bool useMagnet;
    private const float u0 = 0.000001f; //çœŸç©ºã®é€ç£ç‡ ç´„1.26 10^-6 N/A^2
    private float q; //ç£è·ã€€kai * H_pow  SIâ†’Wb CGSâ†’emu
    private float shita_x; //å›è»¢æ–¹å‘(xè»¸åŸºæº–)ã«å¯¾ã™ã‚‹é–ã®è§’åº¦
    private float shita_y; //å›è»¢è»¸(zè»¸)ã«å¯¾ã™ã‚‹é–ã®è§’åº¦
    private float dist;
    private Vector3 PosVect; //ç²’å­é–“ã®å·®åˆ†ãƒ™ã‚¯ãƒˆãƒ«
    private Vector3 E; //å˜ä½ãƒ™ã‚¯ãƒˆãƒ«
    private Vector3 M0, M1, M2; //ç£æ°—åŒæ¥µå­ãƒ¢ãƒ¼ãƒ¡ãƒ³ãƒˆ Wb*m
    private Vector3[] H, dH; // ç£ç•Œ = m/(4Ï€Î¼0r^2) = 1/mr^2?
    public float default_H_pow; //å¤–éƒ¨ç£å ´ã®å¼·ã•ã®åˆæœŸå€¤ 60
    [HideInInspector] public float kai; //å˜ä½è³ªé‡ç£åŒ–ç‡ã€€Dynabeadsã®å ´åˆ 50 (emu/g)/G = (A*m^2/kg)/G
    public float thDist; //é–¾å€¤ï¼ˆç£å ´å½±éŸ¿ç¯„å›²ï¼‰
    public float tooNearDist;
    public float rotationSpeed; //å›è»¢é€Ÿåº¦
    public float TargetMag, ChangeMag; //æ™‚é–“å¤‰åŒ–ç£å ´ã®å¤‰åŒ–é‡
    public bool onStartMag; //åˆæœŸç£å ´æ¡ä»¶ åˆ‡ã‚Šæ›¿ãˆ
    public bool useRotation; //å›è»¢ç£å ´ åˆ‡ã‚Šæ›¿ãˆ
    public bool useTimeChangeMag; //æ™‚é–“å¤‰åŒ–ç£å ´ åˆ‡ã‚Šæ›¿ãˆ
    [HideInInspector] public float H_pow; //å¤–éƒ¨ç£å ´ã®å¼·ã•(G) 70 A/m =  ç´„1 G
    public GameObject MagnetOBJ;
    public Transform MagnetOBJTrans;
    public bool useMagnetOBJ;
    Vector3[] M_ofParticles;

    //Save value
    public bool saveParticlePosition; //ç£å ´ä¿å­˜ åˆ‡ã‚Šæ›¿ãˆ
    [HideInInspector] public string[,] AllParticlePosition;
    public bool saveBrown;
    string dirN;
    int stepN;
    StreamWriter swP;

    private void Start()
    {
        step = 0;
        //ã‚»ãƒƒãƒˆã•ã‚ŒãŸç²’å­ã‚ªãƒ–ã‚¸ã‚§ã‚¯ãƒˆã¨ãã®æ•°ã‚’å–å¾—
        if (setParticle.set)
        {
            particleNumber = setParticle.MagneticParticle.Length;
            MagneticParticle = new GameObject[particleNumber];
            for (i = 0; i < particleNumber; i++)
            {
                MagneticParticle[i] = setParticle.MagneticParticle[i];
            }
        } else
        {
            particleNumber = MagneticParticle.Length;
        }

        //ç²’å­æ•°ã‚’ã‚‚ã¨ã«ç£å ´ãªã©ã®é…åˆ—ã‚µã‚¤ã‚ºã‚’å®šç¾©
        brownX = new Vector3[particleNumber];
        H = new Vector3[particleNumber];
        dH = new Vector3[particleNumber];
        MagneticParticleRB = new Rigidbody[particleNumber];
        MagneticParticleTrans = new Transform[particleNumber];
        BeforePosition = new Vector3[particleNumber];
        brownX_before = new Vector3[particleNumber];
        AllParticlePosition = new string[SimulationController.MaxStep, particleNumber];

        //MPRBã‚’å–å¾—, åˆæœŸä½ç½®ã‚’ä»£å…¥
        for (i = 0; i < particleNumber; i++)
        {
            MagneticParticleRB[i] = MagneticParticle[i].GetComponent<Rigidbody>();
            MagneticParticleTrans[i] = MagneticParticle[i].GetComponent<Transform>();
            BeforePosition[i] = MagneticParticle[i].transform.position;
        }

        //å›è»¢ç”¨ è§’åº¦è¨­å®šï¼ˆ30åº¦ï¼‰
        //shita_y = 30 * Pi / 180;

        //ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿è¨­å®š
        thDist = thDist * diameter;
        diameter = diameter * MCoefficient;
        gamma = 6 * Pi * (diameter / 2) * eta;
        D = kb * T / gamma;
        kai = 50 * 1 * KgCoefficient;//å˜ä½è³ªé‡ç£åŒ–ç‡â†’ç£åŒ–ç‡(emu/G)ã¸ï¼ˆç²’å­è³ªé‡1kg*è³ªé‡ä¿‚æ•°ï¼‰

        //ç£å ´ã®åˆæœŸæ¡ä»¶
        if (onStartMag)
            ONMag();
        else
            OFFMag();

        if (saveBrown)
        {
            stepN = 0;
            dirN = DateTime.Now.Month.ToString() + "_" + DateTime.Now.Day.ToString() + "_" + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString();
            Directory.CreateDirectory(dirN);
            swP = new StreamWriter(dirN + "/particle_position_" + DateTime.Now.Month.ToString() + "_" + DateTime.Now.Day.ToString() + "_" + DateTime.Now.Hour.ToString() + DateTime.Now.Minute.ToString() + ".csv");
        }

        M_ofParticles = new Vector3[particleNumber];
    }

    private void FixedUpdate()
    {
        step = SimulationController.Step;
        stepTime = Time.deltaTime; //1ã‚¹ãƒ†ãƒƒãƒ—ã®æ™‚é–“

        if (saveBrown)
        {
            string s = (stepN * stepTime).ToString("F3");
            s += ",";
            float r = 0;
            for (j = 0; j < particleNumber; j++)
            {
                //s += ",";
                //s += j;
                //s += ",";
                //s += MagneticParticleTrans[j].position.x.ToString("F3");
                //s += ",";
                //s += MagneticParticleTrans[j].position.y.ToString("F3");
                //s += ",";
                //s += MagneticParticleTrans[j].position.z.ToString("F3");
                r += Vector3.SqrMagnitude(MagneticParticleTrans[j].position);
            }
            s += (r/particleNumber).ToString("F5");
            swP.WriteLine(s);

            if (stepN * stepTime >= 5)
            {
                saveBrown = false;
                swP.Close();
                Debug.Log("endSave");
            }

            stepN++;
        }

        if (saveParticlePosition) //ç²’å­ä½ç½®ã‚’ä¿å­˜
        {
            SaveParticlePosition();
        }

        if (useTimeChangeMag) //æ™‚é–“å¤‰åŒ–ç£å ´
        {
            if (H_pow <= TargetMag) //ChangeStepã¾ã§ChangeMagãšã¤å¢—åŠ 
                H_pow += stepTime * ChangeMag;
            else
            {
                H_pow = TargetMag;
                useTimeChangeMag = false;
            }
            ChangeMagneticField();
        }

        if (useBrown || useTrans)
        {
            Noise(); //ãƒ–ãƒ©ã‚¦ãƒ³é‹å‹•
        }

        if (useRandPow)
        {
            RandomPow();
        }

        if (useMagnet)
        {
            Interactive(); //ç£æ°—ç›¸äº’ä½œç”¨
        }
    }

    private void Update()
    {
        ////ç£å ´æ–¹å‘åˆ‡ã‚Šæ›¿ãˆ
        //if (Input.GetKeyDown(KeyCode.X))
        //{
        //    shita_x = 0f;
        //    shita_y = 90f;
        //    ChangeMagneticField();
        //}
        //if (Input.GetKeyDown(KeyCode.Y))
        //{
        //    shita_x = 90f;
        //    shita_y = 90f;
        //    ChangeMagneticField();
        //}
        //if (Input.GetKeyDown(KeyCode.Z))
        //{
        //    shita_x = 0f;
        //    shita_y = 0f;
        //    ChangeMagneticField();
        //}

        //ç£å ´æ–¹å‘åˆ‡ã‚Šæ›¿ãˆ
        if (Input.GetKeyDown(KeyCode.X))
        {
            shita_x = 0f;
            shita_y = 90f;
            ChangeMagneticField();
        }
        if (Input.GetKeyDown(KeyCode.Y))
        {
            shita_x = 90f;
            shita_y = 0f;
            ChangeMagneticField();
        }
        if (Input.GetKeyDown(KeyCode.Z))
        {
            shita_x = 0f;
            shita_y = 0f;
            ChangeMagneticField();
        }
    }

    private void Noise() //ãƒ–ãƒ©ã‚¦ãƒ³é‹å‹•
    {
        for (n = 0; n < particleNumber; n++)
        {
            nowPos = MagneticParticleTrans[n].position;
            V = (nowPos - BeforePosition[n]) * MCoefficient / stepTime;
            BeforePosition[n] = nowPos;

            //ãƒœãƒƒã‚¯ã‚¹ãƒŸãƒ¥ãƒ©ãƒ¼æ³•ï¼ˆä¸€æ§˜åˆ†å¸ƒã®ä¹±æ•°ã‚’æ¨™æº–æ­£è¦åˆ†å¸ƒã¸ 
            x = Mathf.Sqrt(-2.0f * Mathf.Log(UnityEngine.Random.Range(0.00001f, 1.0f))) * Mathf.Cos(2.0f * Pi * UnityEngine.Random.Range(0f, 1.0f));
            y = Mathf.Sqrt(-2.0f * Mathf.Log(UnityEngine.Random.Range(0.00001f, 1.0f))) * Mathf.Cos(2.0f * Pi * UnityEngine.Random.Range(0f, 1.0f));
            z = Mathf.Sqrt(-2.0f * Mathf.Log(UnityEngine.Random.Range(0.00001f, 1.0f))) * Mathf.Cos(2.0f * Pi * UnityEngine.Random.Range(0f, 1.0f));

            //ãƒ©ãƒ³ã‚¸ãƒ¥ãƒãƒ³æ–¹ç¨‹å¼ã®è§£ ã€ˆ(ğ‘¥(ğ‘¡) âˆ’ ğ‘¥(0))^2ã€‰ = 2ğ·|ğ‘¡|
            x = Mathf.Sqrt(stepTime * 2 * D) / MCoefficient * x;
            y = Mathf.Sqrt(stepTime * 2 * D) / MCoefficient * y;
            z = Mathf.Sqrt(stepTime * 2 * D) / MCoefficient * z;
            brownX[n] = new Vector3(x, y, z);

            //ä½ç½®åˆ¶å¾¡
            if (useTrans)
            {
                MagneticParticleTrans[n].transform.Translate(brownX[n]);
            }
            else
            {
                MagneticParticleRB[n].AddForce((brownX[n]) / stepTime, ForceMode.VelocityChange);
            }

            //é€Ÿåº¦åˆ¶å¾¡
            //pow += x;
            //pow += y;
            //pow += z;
            //MagneticParticleRB[n].AddForce((brownX[n]) / stepTime, ForceMode.VelocityChange);
            //MagneticParticleRB[n].AddForce((brownX[n] - brownX_before[n]) / stepTime, ForceMode.VelocityChange);

            //brownX_before[n] = brownX[n];
        }
    }

    private void RandomPow()
    {
        for (n = 0; n < particleNumber; n++)
        {
            Vector3 RandomPow = new Vector3(UnityEngine.Random.Range(-pow, pow), UnityEngine.Random.Range(-pow, pow), UnityEngine.Random.Range(-pow, pow));

            MagneticParticleRB[n].AddForce(RandomPow);
        }
    }

    public void Interactive() //ç£æ°—ç›¸äº’ä½œç”¨
    {
        for (i = 0; i < particleNumber; i++) //Hã‚’åˆæœŸåŒ–
        {
            H[i] = new Vector3(0f, 0f, 0f);

            //ç£çŸ³-ç²’å­é–“ç›¸äº’ä½œç”¨ è¿½åŠ 23/9/28
            if (useMagnetOBJ)
            {
                PosVect = MagneticParticleTrans[i].position - MagnetOBJTrans.position;
                dist = Mathf.Sqrt(Vector3.Dot(PosVect, PosVect));
                E = PosVect / dist;
                dist = dist * MCoefficient;
                M_ofParticles[i] = kai * H_pow * (-1f / 4f * Pi * u0) * ((M0/dist*dist*dist)-(3*Vector3.Dot(M0, PosVect)*PosVect/dist * dist * dist * dist * dist));
                M1 = M_ofParticles[i];
                H[i] = (3f * u0 / (4f * Pi * dist * dist * dist * dist)) * (Vector3.Dot(M1, E) * M0
                     + Vector3.Dot(M0, E) * M1 + Vector3.Dot(M1, M0) * E
                     - 5f * Vector3.Dot(M1, E) * Vector3.Dot(M0, E) * E);
            }
        }

        //ç²’å­é–“ç›¸äº’ä½œç”¨
        for (i = 0; i < particleNumber; i++)
        {
            for (j = i + 1; j < particleNumber; j++)
            {
                if (useMagnetOBJ)
                {
                    M1 = M_ofParticles[i];
                    M2 = M_ofParticles[j];
                }               

                PosVect = MagneticParticleTrans[i].position - MagneticParticleTrans[j].position;
                dist = Mathf.Sqrt(Vector3.Dot(PosVect, PosVect));
                if (dist < thDist)
                {
                    E = PosVect / dist;
                    dist = dist * MCoefficient;

                    dH[i] = (3f * u0 / (4f * Pi * dist * dist * dist * dist)) * (Vector3.Dot(M1, E) * M2
                          + Vector3.Dot(M2, E) * M1 + Vector3.Dot(M1, M2) * E
                          - 5f * Vector3.Dot(M1, E) * Vector3.Dot(M2, E) * E);

                    H[i] += dH[i];
                    H[j] -= dH[i];
                }
            }
            MagneticParticleRB[i].AddForce(H[i] / KgCoefficient);
            //Debug.Log(H[i]/KgCoefficient);
        }
    }

    public void ChangeMagneticField()
    {
        //å‡ä¸€ç£å ´
        //q = kai * H_pow;

        //shita_y = Mathf.Deg2Rad * shita_y;
        //shita_x = Mathf.Deg2Rad * shita_x;

        //x = (q * diameter / u0) * Mathf.Sin(shita_y) * Mathf.Cos(shita_x);
        //y = (q * diameter / u0) *                      Mathf.Sin(shita_x);
        //z = (q * diameter / u0) * Mathf.Cos(shita_y);

        //M1 = new Vector3(x, y, z);
        //M2 = M1;

        if (!useMagnetOBJ)
        {
            //å‡ä¸€ç£å ´
            q = kai * H_pow;

            shita_y = Mathf.Deg2Rad * shita_y;
            shita_x = Mathf.Deg2Rad * shita_x;

            x = (q * diameter / u0) * Mathf.Sin(shita_y);
            y = (q * diameter / u0) * Mathf.Sin(shita_x);
            z = (q * diameter / u0) * Mathf.Cos(shita_y) * Mathf.Cos(shita_x);

            M1 = new Vector3(x, y, z);
            M2 = M1;
        } else
        {
            //ä¸å‡ä¸€ç£å ´
            Vector3 MagnetRotation = MagnetOBJ.GetComponent<Transform>().rotation.eulerAngles;
            shita_y = MagnetRotation.y;
            shita_x = MagnetRotation.x;

            M0 = new Vector3(Mathf.Sin(shita_y), Mathf.Sin(shita_x), Mathf.Cos(shita_y) * Mathf.Cos(shita_x)) * H_pow;
        }
    }

    public void ONMag()
    {
        ON_MagButton.interactable = false;
        OFF_MagButton.interactable = true;
        TimeMagButton.interactable = false;
        H_pow = default_H_pow;
        useTimeChangeMag = false;
        ChangeMagneticField();
    }

    public void OFFMag()
    {
        ON_MagButton.interactable = true;
        OFF_MagButton.interactable = false;
        TimeMagButton.interactable = true;
        H_pow = 0;
        useTimeChangeMag = false;
        ChangeMagneticField();
    }

    public void UseTimeChangeMag()
    {
        TimeMagButton.interactable = false;
        useTimeChangeMag = true;
        H_pow = 0;
    }

    public void SaveParticlePosition()
    {
        int s;
        for (s = 0; s < particleNumber; s++)
        {
            string z;
            if (MagneticParticle[s].transform.position.z < 0)
                z = "2";
            else
                z = "3";
            string[] s1 = { string.Format("{0, 4}", s.ToString()), z, string.Format("{0,7}", MagneticParticle[s].transform.position.z.ToString("F4")), string.Format("{0,7}", MagneticParticle[s].transform.position.x.ToString("F4")), string.Format("{0,7}", MagneticParticle[s].transform.position.y.ToString("F4")), };
            string s2 = string.Join(" ", s1);
            AllParticlePosition[step, s] = s2;
        }
    }
}
